### ISSUE TITLE
LUA error when I mouseover an achievement in chat

### ISSUE THREAD

**Issue by Galiwyx** [Auctionator/Auctionator#445] opened 2020-01-28 17:48 UTC
Hello,

- Auctionator (version from 2 days ago)
- I use ElvUi

When I mouseover an achievement on the chat, I've an LUA Error : 

`Message: ...dOns\Auctionator\Source\Utilities\ItemIdFromLink.lua:2: bad argument #1 to 'find' (string expected, got nil)
Time: Tue Jan 28 18:44:32 2020
Count: 2
Stack: ...dOns\Auctionator\Source\Utilities\ItemIdFromLink.lua:2: bad argument #1 to 'find' (string expected, got nil)
[string "=[C]"]: ?
[string "=[C]"]: in function `find'
[string "@Interface\AddOns\Auctionator\Source\Utilities\ItemIdFromLink.lua"]:2: in function `ItemIdFromLink'
[string "@Interface\AddOns\Auctionator\Source\Tooltips\Hooks.lua"]:243: in function <...terface\AddOns\Auctionator\Source\Tooltips\Hooks.lua:241>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetHyperlink'
[string "@Interface\AddOns\ElvUI\Modules\chat\Chat.lua"]:1082: in function `?'
[string "@Interface\AddOns\AddOnSkins\Libs\Ace3\AceHook-3.0\AceHook-3.0.lua"]:90: in function <...Ons\AddOnSkins\Libs\Ace3\AceHook-3.0\AceHook-3.0.lua:87>

Locals: `

Hope It helps you
Thank you

**Comment by plusmouse** [comment] 2020-01-28 20:06
This is a duplicate of #440

**Closed by plusmouse** 2020-01-28 20:06 UTC
Labels: bug, duplicate
