### ISSUE TITLE
Action Forbidden

### ISSUE THREAD

**Issue by lightyear66** [Auctionator/Auctionator#1304] opened 2022-12-15 08:49 UTC
Please include as much of the following information as possible to help me fix the bug:

## Are you on the retail or the classic version of WoW?
Retail - Dragonflight

## Is this a bug or a feature request?

# Bug:
## Brief Description of Bug
Sometimes when I right click an object such as an enchant to apply it to one of my equipment the blizz UI pops up a warning that the auctionator addon has tried to perform an action not allowed - I'm given the option to disable the addon or cancel the action of right-clicking the enchantment.

_Please include a brief description of the bug, including what you were doing, and when it occurred._

Happens about 25% of the time when trying to right click objects in inventory for use or application.
Disabling Auctionator fixes problem 100% of time.

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._
right click on an enchant before attempting to apply it to an item

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._
Auctionator
BugGrabber
BugSack
Details! Damage Meter
Gathermate2
Handynotes
Leatrix Plus
MapCoords
Plater
Postal
Premade Group Finder
Raider.IO
Rarescanner
Talent Tree Tweaks
Unlimited Map Distance
WeakAuras
Speedy Autoloot
Deadly Boss Mods

## Back Trace (LUA Error Output)
Bugcatcher:
6x [ADDON_ACTION_FORBIDDEN] AddOn 'Auctionator' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@FrameXML/ContainerFrame.lua"]:1409: in function <FrameXML/ContainerFrame.lua:1318>
[string "=[C]"]: in function `ContainerFrameItemButton_OnClick'
[string "@FrameXML/ContainerFrame.lua"]:1461: in function <FrameXML/ContainerFrame.lua:1448>

_You can get this through the use of !BugGrabber and BugSack addons._

# Feature Request:
## Is your feature request related to a problem? Please describe
Describe the problem you are experiencing.

**Comment by nik-11** [comment] 2022-12-19 04:46
Same issue here, it can happen on any "on use" item in my bags. UI reload usually fixes it for a bit, but can happen again and again.

**Comment by plusmouse** [comment] 2022-12-19 12:26
I've hit this issue too, but haven't been able to identify the trigger yet. The cause is something else and the unable to use a bag item is the symptom.

Do you remember if you used
1. The auction house in the session before the error? If you did use the auction house, did you buy something? Cancel something? Post something?
2. Used the professions view (seeing crafting and profits values)?
3. Used work orders (seeing the reagents cost)?
4. Opened the guild bank (viewing tooltips)?

Anything else (basically anything you may have seen information or UI components from Auctionator on)?

Hopefully with enough different answers to the above questions I should be able to narrow down what the trigger is.

**Comment by Deusdictum** [comment] 2022-12-24 06:57
It sometimes even happens during combat blocking the usage of any spells and abilities.

**Comment by lightyear66** [comment] 2022-12-31 21:39
I have been keeping track of almost each instance where this error occurs.
I do not see an obvious pattern.
Here is a record:


   - bought WOW token
   - retrieved from mail
   - used WOW token
   - fail:  attempted to turn rousing fire into awakened fire



   - repaired on repair mount
   - entered M+ instance
   - fail: tried to use Phial



   - flying
   - land and pick herb
   - receive bonus dreambloom petal
   - fail: try to use dreambloom petal



   - buy gem from AH
   - retrieve gem from mail
   - socket gem
   - close bag
   - open bag
   - fail:  try to use Aylaag Windstone Fragment



   - enter M+ instance
   - fail:  try to use Phial



   - enter M+instance
   - fail: try to use Endless Stack of Needles



   - enter M+ instance
   - fail: tru to use Phial



   - post several AH auction
   - teleport to top of Valdrakken tower
   - fail: try to use Aylaag Windstone fragment



   - took portal from Stormwind to Valdrakken
   - fail: tried to use Endless Stack of needles



   - Accept summons
   - Enter M+ instance
   - fail: try to use Phial


I doubt this helps much - but I thought I would send anyhow.  Seems
slightly more likely to happen after using a portal or entering an
instance, but maybe I just often try to use items in my inventory after
these actions.

Thanks for the nice addon anyhow,

Todd

**Comment by plusmouse** [comment] 2022-12-31 22:14
Thanks for the summary. I'll try the different scenarios out and see if I can get a trigger from one of them.

I have read about other addons having protected errors trigger after some kind of loading screen.

**Comment by corveroth** [comment] 2023-01-04 10:56
There are a variety of taint bugs in the 10.x interface, and by the nature of taint, they often spread and implicate innocent addons. This repo attempts to track them: https://github.com/Stanzilla/WoWUIBugs/issues

**Comment by plusmouse** [comment] 2023-01-08 14:34
I've pushed a fix for the blocked error triggering after a purchase in some scenarios. This may help with the blocked errors. Please report back if you get a blocked error after installing [10.0.29](https://www.curseforge.com/wow/addons/auctionator/files/4318860)

**Closed** 2023-01-25 11:46 UTC
Labels: bug, retail
