### ISSUE TITLE
Search results show wrong quality/rarity

### ISSUE THREAD

**Issue by kaizengamer** [Auctionator/Auctionator#228] opened 2016-09-26 15:34 UTC
Searching all of AH for any armor ilvl 759+ and requires level 101+.

https://youtu.be/NOYP-q4Qa1A

If any of the available/found versions of the item are epic, the search results will show them all as epic.  

In actuality, the 450G one listed is blue/rare quality and the 2500G listed one is purple/epic quality.

**Comment by ceylina** [comment] 2016-09-26 17:48
Duplicate of known issues but thanks for posting.

**Closed by ceylina** 2016-09-26 17:48 UTC
