### ISSUE TITLE
Auctionator not calculating deposits correctly

### ISSUE THREAD

**Issue by sauljaffe** [Auctionator/Auctionator#883] opened 2020-10-17 16:50 UTC
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

Auctionator not calculating deposits correctly.

## Steps to Reproduce

I was looking at selling a large amount of Frostweave Cloth (1687).  Auctionator, on the Selling tab showed the deposit was calculated as 126g 53s

I tried looking at the same thing on the "Sell" tab, and the deposit for the same amount of Frostweave Cloth there was calculated as: 63g 27s

Oddly, the Buyout price for one unit on the "Selling" tab was less than what was shown on the "Sell" tab. (74s, vs 77s).

![image](https://user-images.githubusercontent.com/26287341/96348789-4df63380-1079-11eb-8ff0-ad145720f8e5.png)

![image](https://user-images.githubusercontent.com/26287341/96348799-61090380-1079-11eb-8acf-55de6dc6baad.png)

**Comment by plusmouse** [comment] 2020-10-17 16:58
You can paste screenshots into the issue box. Please do so.

**Comment by plusmouse** [comment] 2020-10-17 18:26
Looking at the screenshots.
1. Different duration used in the Selling tab vs Sell tab (which explains the different deposits)
2. Do you have any undercut settings active - that would explain the different starting price?

**Comment by plusmouse** [comment] 2020-10-18 20:22
Not a bug (just some settings in Auctionator changed). Closing.

**Closed by plusmouse** 2020-10-18 20:22 UTC
Labels: release
