### ISSUE TITLE
broken frames when using with TSM

### ISSUE THREAD

**Issue by hollo6** [Auctionator/Auctionator#1398] opened 2023-06-07 10:52 UTC
## Brief Description of Bug
After switching from TSM window to an Auctionator tab, the frame gets broken and nothing but a reload fixes it.
![image](https://github.com/Auctionator/Auctionator/assets/365584/db64224b-93bd-4b5a-a703-9ae3c36316a1)

Sometimes it's this element, sometimes one of the buttons but one of them always looks like this.
This behavior appeared with TSM v4.12.38 and is still present with 4.12.39, but not 4.12.37. TSM frames and all functionality are intact.
Auctionator version doesn't seem to impact it, I've tried to roll back several versions but it didn't help. Currently using v10.1.5-12-g914353a.
I know this shouldn't be an issue with this addon but TSM will obviously not fix it since theirs "works as intended" and I really don't want to be stuck using an old version of it for years again, so... I'm hoping there's something that can be done about this on your end.

## Steps to Reproduce
1. Open AH with TSM window (it should be the first one appearing when interacting with the NPC, so switching to TSM window and reopening the AH might be necessary)
2. Switch to default UI / Auctionator
3. Observe broken frame / button

## Loaded Addons
Auctionator
BugGrabber
BugSack
TradeskillMaster

## Back Trace (LUA Error Output)
There is no LUA error.

**Comment by plusmouse** [comment] 2023-06-07 11:43
The issue arises when Auctionator isn't loaded, and is related to buttons autosizing on creation:

This mini addon will trigger the issue with Auctionator disabled on a first load in the client.
[AHTab-b491886.zip](https://github.com/Auctionator/Auctionator/files/11676551/AHTab-b491886.zip)

**Comment by hollo6** [comment] 2023-06-07 12:15
Yes it's changed in TSM v4.12.38.
Reopening the AH doesn't fix this, nothing does except reload sadly.

**Comment by hollo6** [comment] 2023-06-07 12:18
> The issue arises when Auctionator isn't loaded, and is related to buttons autosizing on creation:
> 
> This mini addon will trigger the issue with Auctionator disabled on a first load in the client. [AHTab-b491886.zip](https://github.com/Auctionator/Auctionator/files/11676551/AHTab-b491886.zip)

So what you're saying is if I were to use this addon, it would "mask" the issue and Auctionator frames would work?

**Comment by plusmouse** [comment] 2023-06-07 12:22
No, it won't fix the issue, but it demonstrates that the issue isn't specific to Auctionator, another add-on adding tabs to the ah would be affected too

**Comment by plusmouse** [comment] 2023-06-07 16:41
Try this build:
[Auctionator-10.1.5-14-g858220b.zip](https://github.com/Auctionator/Auctionator/files/11679926/Auctionator-10.1.5-14-g858220b.zip)

**Comment by plusmouse** [comment] 2023-06-07 16:52
Fixed in the latest alphas, available from Curseforge or Wago when the build finishes processing.

**Closed by plusmouse** 2023-06-07 16:52 UTC
Labels: retail

**Comment by hollo6** [comment] 2023-06-07 16:56
It works!
You are awesome, thank you!
