### ISSUE TITLE
No difference between 2 items with same name but different iLvL

### ISSUE THREAD

**Issue by Kred88** [Auctionator/Auctionator#792] opened 2020-07-18 09:54 UTC
![image](https://user-images.githubusercontent.com/15103035/87850040-6b3a2b00-c8ed-11ea-8f0b-4542d90b78d5.png)

**Comment by plusmouse** [comment] 2020-07-18 10:07
Duplicate of #611

**Closed by plusmouse** 2020-07-18 10:07 UTC
