### ISSUE TITLE
Default quantity setting

### ISSUE THREAD

**Issue by sauljaffe** [Auctionator/Auctionator#804] opened 2020-07-27 17:24 UTC
**Is your feature request related to a problem? Please describe.**
I don't always put up for sale in the auction house all of an item.  Sure, for mats that's fine but for pets, no.  I prefer to only put one pet up for sale at a time.  That is to say if I have two or more of a pet, I only put up one.

**Describe the solution you'd like**
I'd like to see different default settings in the Selling tab for quantity based on the type of item so that mats can have a different default quantity from pets or other items.

**Describe alternatives you've considered**
I can manually set the quantity each time but it's more work, especially when in a hurry.  And, I've forgotten to change the setting several times now so that more items went up for sale than I intended.

**Comment by plusmouse** [comment] 2020-07-27 17:57
Duplicate of #605 
Duplicate of #797

**Comment by plusmouse** [comment] 2020-07-27 18:00
Making custom quantities for specific categories is on the to-do list.

The fix for #797 is a workaround until that feature comes out.

**Closed by plusmouse** 2020-07-27 18:00 UTC
Labels: enhancement
