### ISSUE TITLE
Bought wrong items after full scan

### ISSUE THREAD

**Issue by mogge182** [Auctionator/Auctionator#1469] opened 2023-12-23 09:37 UTC
## Brief Description of Bug

After a full scan, I went to the shopping tab to buy Greater Magic Essence. When I searched for the items they showed up as they should. But when I clicked buy, everything froze for a couple of seconds and a timer showed. I bought 3 Greater Magic Essences and the same behaviour on each buy. So I closed the Auctionator window and retried, and bought 35 Greater Magic Essences and everything worked as it should. When I went to the mailbox to retrieve the items I saw that I had bought 35  Magic Essences (should have need 38) 1 Aquadynamic Fish Attractor, 1 Bronze Tube, 1 Heavy leather. 

## Steps to Reproduce

Haven't been able to reproduce

## Loaded Addons

 - DBM
 - AtlasLoot
 - Details
 - ElvUi
 - NeatPlates
 - Pawn
 - Questie
 - WeakAuras

**Comment by plusmouse** [comment] 2023-12-23 09:46
What's your version of Auctionator (when the error happened)? This is unlikely to be the cause, but for diagnosing the bug its needed.

**Comment by mogge182** [comment] 2023-12-23 12:13
> What's your version of Auctionator (when the error happened)? This is unlikely to be the cause, but for diagnosing the bug its needed.

 version 10.2.6

**Comment by plusmouse** [comment] 2023-12-23 17:58
Thanks. Did you have any of these listed as your own auctions
> 1 Aquadynamic Fish Attractor, 1 Bronze Tube, 1 Heavy leather.

**Comment by mogge182** [comment] 2023-12-24 10:00
> Thanks. Did you have any of these listed as your own auctions
> 
> > 1 Aquadynamic Fish Attractor, 1 Bronze Tube, 1 Heavy leather.

I didn’t have any auctions at all.

**Comment by plusmouse** [comment] 2024-05-11 17:16
As this issue hasn't repeated going to close it as unlucky

**Closed by plusmouse** 2024-05-11 17:16 UTC
Labels: classic
