### ISSUE TITLE
1. AH Button offscreen if AH is open/2. Open AH and Trade Skill UI/3. Auctionator

### ISSUE THREAD

**Issue by Heavy735** [Auctionator/Auctionator#123] opened 2016-07-21 20:13 UTC
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by ceylina** [comment] 2016-07-22 01:10
I think the question is stating that the AH button when opening tradeskill windows is showing offscreen on certain monitor sizes.

**Comment by ceylina** [comment] 2016-07-22 01:20
Please reply with your screen resolution and what version of Auctionator you are using. I am unable to reproduce even at 800x600 resolution. A screen shot would also be very useful.

**Comment by jrob8577** [comment] 2016-07-23 15:23
@Heavy735 Can we get your screen resolution and Auctionator version? We are trying to reproduce this.  Thanks!

**Comment by jrob8577** [comment] 2016-07-23 21:30
Closing; please re-open with the requested info.

**Closed by jrob8577** 2016-07-23 21:30 UTC
Labels: question
