### ISSUE TITLE
Shopping tab doesn't load at <= 768 height resolution

### ISSUE THREAD

**Issue by blaw-84** [Auctionator/Auctionator#833] opened 2020-08-18 00:39 UTC
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

Shopping tab fails to display any items when running the game at any height resolution of 768 or below (e.g. 1366x768, 1280x768, etc). This only happens when the interface -loads- at such height; rescaling doesn't fix/break it until after you /reload.

## Steps to Reproduce

Go to Main Menu > System > Graphics and change either the Window Size or Resolution Scale to something with height <= 768. Alternatively if playing windowed you can resize the window manually (affecting Resolution scale). Type /reload if necessary.

Also, after loading with a height <= 768, you can change the res/scale to > 768 and apply. Shopping tab still won't load items until you /reload.

## Loaded Addons

I was able to make this happen with only Auctionator loaded.

## Back Trace (LUA Error Output)

No bugs are displayed in BugSack.

**Comment by plusmouse** [comment] 2020-08-18 08:39
I think this is a duplicate of #714 . Do you have the UI scale set to 1.0?

![image](https://user-images.githubusercontent.com/60280559/90490615-b8046200-e136-11ea-969d-88df07c73ccf.png)

**Comment by blaw-84** [comment] 2020-08-19 06:36
@plusmouse I did not have the UI Scale option checked. I tried this and did some testing and found some interesting results. At different resolutions it fails under different times. Here is a summary of my testing:

1. **1920x1080 (fullscreen)**: UI Scale disabled: PASS. UI Scale enabled and = 1.0: **FAIL**. UI Scale Scale enabled and <> 1.0: PASS.
2. **Any resolution with height >768 (windowed)**: same as #1 above.
3. **1280x768 or 800x600 (windowed)**: UI Scale disabled: **FAIL**. UI Scale enabled and = 1.0: **FAIL**. UI Scale enabled and <> 1.0: PASS.
4. **smallest resolution of 720x576 (windowed)**: UI Scale disabled: **FAIL**. UI Scale enabled and = 1.0: PASS. Scale enabled and <> 1.0: PASS.

I hope this is helpful.

**Comment by plusmouse** [comment] 2020-08-19 08:38
I've put a fix in the latest alpha release (278)

**Closed** 2020-08-19 08:37 UTC
Labels: bug
