### ISSUE TITLE
Request: Bidding Amount

### ISSUE THREAD

**Issue by DiggityMan420** [Auctionator/Auctionator#989] opened 2021-02-06 22:33 UTC
I would like to start off saying thank you this is an amazing addon for the auction House. I was  wondering if you would be able to implement a bid amount or make it so we can use a bid amount on the selling tab. i use that tab the most unless i want to bid then i got to go thru other ways. You can set bids in the buy tab but it be nice to add a bid / buyout in the selling tab. Thank you

**Comment by plusmouse** [comment] 2021-02-10 08:19
This is a duplicate of #885 - please comment there.

**Closed by plusmouse** 2021-02-10 08:19 UTC
Labels: enhancement
