### ISSUE TITLE
Auctionatorhints.lua error with indexing Auctionator.Constants.DisenchantingProbability[ classID ]

### ISSUE THREAD

**Issue by ceylina** [Auctionator/Auctionator#103] opened 2016-07-19 21:18 UTC
Reported from the comments section
http://mods.curse.com/addons/wow/auctionator?comment=5929

Version 4.0.0

 Interface\AddOns\Auctionator\AuctionatorHints.lua:242: attempt to index field 'DisenchantingProbability' (a nil value)
Time: 07/19/16 19:35:27
Count: 41
Stack: Interface\AddOns\Auctionator\AuctionatorHints.lua:286: in function `Atr_CalcDisenchantPrice'
Interface\AddOns\Auctionator\AuctionatorHints.lua:359: in function `Atr_STWP_GetPrices'
Interface\AddOns\Auctionator\AuctionatorHints.lua:441: in function `Atr_ShowTipWithPricing'
Interface\AddOns\Auctionator\AuctionatorHints.lua:498: in function <Interface\AddOns\Auctionator\AuctionatorHints.lua:496>
[C]: in function `SetBagItem'
Interface\FrameXML\ContainerFrame.lua:1059: in function `UpdateTooltip'
Interface\FrameXML\GameTooltip.lua:241: in function <Interface\FrameXML\GameTooltip.lua:225>

Locals: classID = nil
itemRarity = 3
itemLevel = 1
dePrice = 0
Atr_FindDEentry = <function> defined @Interface\AddOns\Auctionator\AuctionatorHints.lua:241

**Comment by jrob8577** [comment] 2016-07-20 02:24
Unable to reproduce, will close if we can't get more information (added a request for more info in the comment on curse).

**Comment by jrob8577** [comment] 2016-07-21 03:23
Closing until we can get details to reproduce.

**Closed by jrob8577** 2016-07-21 03:23 UTC
Labels: bug, help wanted, question
