### ISSUE TITLE
Inventory list, to the right

### ISSUE THREAD

**Issue by Anatharias** [Auctionator/Auctionator#968] opened 2021-01-09 01:05 UTC
**Is your feature request related to a problem? Please describe.**
I cannot see auctions listings whenever a tooltip is displayed

**Describe the solution you'd like**
Change the inventory, from left, to right for an easier visibility whenever a tooltip is displayed

Currently:
![auctionator](https://user-images.githubusercontent.com/17396591/104078511-5d1ef480-5216-11eb-92df-e6878c9538bc.PNG)

Could be (rough arrangement):
![auctionator - right icons](https://user-images.githubusercontent.com/17396591/104078518-6b6d1080-5216-11eb-8866-e8cf8fc6f5bc.PNG)

This does not especially need to be default, it can be an option in the settings.
Hope this is feasible.
Thanks

**Comment by addonaddict** [comment] 2021-01-11 01:02
i noticed this too, on certain items the tooltips get in the way
perhaps a simple tooltip anchor to a different position would solve this?
rather than reimagining the whole UI

**Comment by plusmouse** [comment] 2021-02-03 14:06
The UI won't be reordered, adjusting the location of the tooltip, maybe though. As the issue of tooltips overlapping is a duplicate of #955 any progress will be tracked there.

**Closed by plusmouse** 2021-02-03 14:06 UTC
Labels: enhancement
