### ISSUE TITLE
Dashboard and Ledger

### ISSUE THREAD

**Issue by Galthariel** [Auctionator/Auctionator#873] opened 2020-10-04 14:29 UTC
While I really don't want Auctionator to became TSM I think it will be nice a Dashboard and a Ledger if doesn't take too much memory? But as a module or extra Addon and not integrated. The reason I'm saying that is more to give freedom for people either install or not a specific feature. Thanks

**Comment by plusmouse** [comment] 2021-02-11 10:06
Duplicate of #866 . Please put any further comments there.

**Closed by plusmouse** 2021-02-11 10:06 UTC
Labels: enhancement
