### ISSUE TITLE
Error on Auction House Close

### ISSUE THREAD

**Issue by Milamber-Unique** [Auctionator/Auctionator#576] opened 2020-03-13 14:33 UTC
Please include as much of the following information as possible to help me fix the bug:

## When closing the Auction House when the Auctionator screen isn't visible (I use TradeSkillMaster normally)

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

Open AH - if TSM already active only TSM frame shows. Close frame and Auctioneer errors as below.
If Standard AH UI is active, error does not trigger (as the frame Auctioneer is trying to do something with is loaded)

## Loaded Addons

!BugGrabber
!KalielsTracker
Accountant
AchieveIt
AdiButtonAuras
AdiButtonAuras_Config
AdvancedInterfaceOptions
Altoholic
Altoholic_Achievements
Altoholic_Agenda
Altoholic_Characters
Altoholic_Grids
Altoholic_Guild
Altoholic_Search
Altoholic_Summary
AngryKeystones
AskMrRobot
Auctionator
AutoBar
AzeriteTooltip
Bazooka
Bazooka_Options
Blizzard_AchievementUI
Blizzard_ArchaeologyUI
Blizzard_ArenaUI
Blizzard_AuctionUI
Blizzard_AuthChallengeUI
Blizzard_BarbershopUI
Blizzard_BattlefieldMinimap
Blizzard_BindingUI
Blizzard_BlackMarketUI
Blizzard_Calendar
Blizzard_ChallengesUI
Blizzard_ClientSavedVariables
Blizzard_Collections
Blizzard_CombatLog
Blizzard_CombatText
Blizzard_CompactRaidFrames
Blizzard_CUFProfiles
Blizzard_DeathRecap
Blizzard_DebugTools
Blizzard_EncounterJournal
Blizzard_GarrisonUI
Blizzard_GlyphUI
Blizzard_GMChatUI
Blizzard_GMSurveyUI
Blizzard_GuildBankUI
Blizzard_GuildControlUI
Blizzard_GuildUI
Blizzard_InspectUI
Blizzard_ItemAlterationUI
Blizzard_ItemSocketingUI
Blizzard_ItemUpgradeUI
Blizzard_LookingForGuildUI
Blizzard_MacroUI
Blizzard_MovePad
Blizzard_ObjectiveTracker
Blizzard_PetBattleUI
Blizzard_PVPUI
Blizzard_QuestChoice
Blizzard_RaidUI
Blizzard_SocialUI
Blizzard_StoreUI
Blizzard_TalentUI
Blizzard_TimeManager
Blizzard_TokenUI
Blizzard_TradeSkillUI
Blizzard_TrainerUI
Blizzard_Tutorial
Blizzard_VoidStorageUI
Blizzard_WowTokenUI
Broker_Currency
BugSack
BuyEmAll
Capping
Capping_Options
Chinchilla
Clique
Collectinator
ColorPickerPlus
CopyPasta
DataStore
DataStore_Achievements
DataStore_Agenda
DataStore_Auctions
DataStore_Characters
DataStore_Containers
DataStore_Crafts
DataStore_Currencies
DataStore_Garrisons
DataStore_Inventory
DataStore_Mails
DataStore_Pets
DataStore_Quests
DataStore_Reputations
DataStore_Spells
DataStore_Stats
DataStore_Talents
DBM-AntorusBurningThrone
DBM-AQ20
DBM-AQ40
DBM-Argus
DBM-Azeroth
DBM-Azeroth-BfA
DBM-BaradinHold
DBM-BastionTwilight
DBM-BlackrockFoundry
DBM-BlackTemple
DBM-BlackwingDescent
DBM-Brawlers
DBM-BrokenIsles
DBM-BWL
DBM-Challenges
DBM-ChamberOfAspects
DBM-Coliseum
DBM-Core
DBM-CrucibleofStorms
DBM-DefaultSkin
DBM-DMF
DBM-Draenor
DBM-DragonSoul
DBM-EmeraldNightmare
DBM-EternalPalace
DBM-EyeOfEternity
DBM-Firelands
DBM-GarrisonInvasions
DBM-GUI
DBM-HeartofFear
DBM-HellfireCitadel
DBM-Highmaul
DBM-Hyjal
DBM-Icecrown
DBM-Karazhan
DBM-MC
DBM-MogushanVaults
DBM-Naxx
DBM-Nighthold
DBM-Nyalotha
DBM-Onyxia
DBM-Outlands
DBM-Pandaria
DBM-Party-BC
DBM-Party-BfA
DBM-Party-Cataclysm
DBM-Party-Classic
DBM-Party-Legion
DBM-Party-MoP
DBM-Party-WoD
DBM-Party-WotLK
DBM-PvP
DBM-Scenario-MoP
DBM-Serpentshrine
DBM-SiegeOfOrgrimmarV2
DBM-StatusBarTimers
DBM-Sunwell
DBM-TerraceofEndlessSpring
DBM-TheEye
DBM-ThroneFourWinds
DBM-ThroneofThunder
DBM-TombofSargeras
DBM-TrialofValor
DBM-Uldir
DBM-Ulduar
DBM-VoA
DBM-VPARNOLD
DBM-VPVEM
DBM-WorldEvents
DBM-ZuldazarRaid
Decursive
Details
Details_DataStorage
Details_EncounterDetails
Details_RaidCheck
Details_Streamer
Details_TinyThreat
Details_Vanguard
DingAnnouncer
Dominos
Dominos_Cast
Dominos_Config
Dominos_Encounter
Dominos_Progress
Dominos_Roll
DropTheCheapestThing
ElitismHelper
Examiner
ExRT
FB_Broker
FishingBuddy
FriendsShare
GatherMate2
GatherMate2_Data
Grid2
Grid2LDB
Grid2Options
Grid2RaidDebuffs
Grid2RaidDebuffsOptions
GSE
GSE_GUI
GSE_LDB
GTFO
HandyNotes
HandyNotes_BattleForAzerothTreasures
HandyNotes_LegionTreasures
HandyNotes_LongForgottenHippogryph
HandyNotes_LostAndFound
HandyNotes_TimelessTreasures
HandyNotes_TreasureHunter
HandyNotes_VisionsOfNZoth
Hekili
Identity-2
InFlight
InFlight_Load
InstanceAchievementTracker
KeystoneHelper
LiteMount
Mekkatorque_Symbol_Helper
MethodDungeonTools
MinimapRangeExtender
Molinari
NameplateSCT
NPCScan
Omen
OmniCC
OmniCC_Config
OPie
oRA3
Overachiever
Overachiever_Cache
Overachiever_Tabs
Overachiever_Trade
Pawn
Postal
Prat-3.0
Prat-3.0_Libraries
PremadeGroupsFilter
QE-DungeonTips
Quartz
QuestCompletist
RaiderIO
RaiderIO_DB_EU_A
RaiderIO_DB_EU_A_R
RaiderIO_DB_EU_H
RaiderIO_DB_EU_H_R
RaiderIO_DB_KR_A
RaiderIO_DB_KR_A_R
RaiderIO_DB_KR_H
RaiderIO_DB_KR_H_R
RaiderIO_DB_TW_A
RaiderIO_DB_TW_A_R
RaiderIO_DB_TW_H
RaiderIO_DB_TW_H_R
RaiderIO_DB_US_A
RaiderIO_DB_US_A_R
RaiderIO_DB_US_H
RaiderIO_DB_US_H_R
Raven
Raven_Options
RepHelper
Routes
RSA
RSA_DeathKnight
RSA_DemonHunter
RSA_Druid
RSA_Hunter
RSA_Mage
RSA_Monk
RSA_Options
RSA_Paladin
RSA_Priest
RSA_Reminders
RSA_Rogue
RSA_Shaman
RSA_Warlock
RSA_Warrior
SavedInstances
Scrap
Scrap_Config
Scrap_Merchant
ShadowedUF_Options
ShadowedUnitFrames
SharedMedia
SharedMedia_Causese
SharedMediaAdditionalFonts
Simulationcraft
Skillet
SmartQuest
StackSize
TellMeWhen
TellMeWhen_Options
TidyPlates_ThreatPlates
TinyPad
TipTac
TipTacItemRef
TipTacOptions
TomTom
TrackOMatic
TrackOMatic_HeartOfAzeroth
TradeSkillMaster
TradeSkillMaster_AppHelper
tullaRange
tullaRange_Config
UniTarget
WeakAuras
WeakAurasArchive
WeakAurasCompanion
WeakAurasModelPaths
WeakAurasOptions
WeakAurasTemplates
WhereToGather
WQAchievements

## Back Trace (LUA Error Output)

3x Auctionator\Source\Core\Mixin.lua:108: attempt to index field 'ShoppingListFrameRef' (a nil value)
[string "@Auctionator\Source\Core\Mixin.lua"]:108: in function <Auctionator\Source\Core\Mixin.lua:103>

Locals:
self = AuctionatorAHFrame {
 0 = <userdata>
 OnShow = <function> defined @Auctionator\Source\Core\Mixin.lua:92
 OnEvent = <function> defined @Auctionator\Source\Core\Mixin.lua:103
}
eventName = "AUCTION_HOUSE_CLOSED"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'ShoppingListFrameRef' (a nil value)"

**Comment by plusmouse** [comment] 2020-03-13 17:59
While I appreciate errors can be annoying, fixing errors caused by the actions of another add-on is out of scope

**Closed by plusmouse** 2020-03-13 17:59 UTC

**Comment by plusmouse** [comment] 2020-03-14 15:56
Also see https://github.com/Auctionator/Auctionator/issues/578
