### ISSUE TITLE
Auctionator crashes client if guild bank is open

### ISSUE THREAD

**Issue by liquidbase** [Auctionator/Auctionator#193] opened 2016-08-28 15:09 UTC
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

Every time I open the guild bank with Auctionator the client become unreponsable. Only way to use the client is to kill the process and disable Auctionator.

## Steps to Reproduce

Open guild bank with Auctionator enabled

## Loaded Addons

Auctionator, DuffedUI, cargbags_Nivaya

## Back Trace (LUA Error Output)

No Lua-Error appears

**Comment by ceylina** [comment] 2016-08-29 03:31
Can you explain this more? You can't open the guild bank with the Auction House open unless you mean with the addon auctionator installed and enabled opening the guild bank hangs wow. If so I cannot reproduce this.

Please disable all addons and only enable auctionator then see if you still have this issue. Cargbags_Nivaya does not interact with the guild bank so we can rule that out.

I suspect your UI compilation or a part thereof is conflicting with Auctionator and we would need to know the specific part to further troubleshoot.

**Comment by ceylina** [comment] 2016-08-29 03:49
Just did a test with the addons you state using and cannot reproduce this. 

Auctionator version 4.0.11, DuffedUI 8.4.7, and Cargbags_Nivaya version 7.0.3 r37

Unless you are also running additional addons, we cannot reproduce this issue.

**Comment by ceylina** [comment] 2016-09-01 15:21
Closing as this is not reproducible.

**Closed by ceylina** 2016-09-01 15:21 UTC
Labels: question
