### ISSUE TITLE
Auctionator using 20% CPU when not in actual use.

### ISSUE THREAD

**Issue by You-Too** [Auctionator/Auctionator#208] opened 2016-09-09 15:15 UTC
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

I installed the addon "AddonUsage" to check how much of my CPU was being used by addons to try and improve the overall performance of the game. (I used the realtime monitor option) The ones using the most when in use (except Auctionator, which by the way goes to 99% CPU when doing a full scan) was WeakAuras and PetTracker. These went down in CPU usage when they weren't actually being used though. MasterPlan was using a bit of the CPU when not in use though, so I removed it. There is no real use for that one anymore anyway so it didn't bother me.

The issue is that Auctionator - according to AddonUsage - is using 20% CPU even when it's not actually being used. I don't even have to go to an auction house, it's at 20% right when I log on. This has lead me to disable the addon while not doing auctions and activate it when I need it.

## Steps to Reproduce

Just log on and go out questing or just anything.

## Loaded Addons

Auctionator
Bagnon
FixStatusBars (extremely lightweight custom addon to make status bars on character portrait only show health/mana percentages on mouseover)
Group Finder Silence
HotLoot (outdated but amazing addon which adds custom options to autoloot)
Maxcam
Overachiever
PetTracker
Skada
Tidy Plates with BlizzardPlates
TomTom
WeakAuras
Deadly Boss Mods incl all the extra old content addons

## Back Trace (LUA Error Output)

Nothing to list here.

**Comment by jrob8577** [comment] 2016-09-09 15:17
I can take a look at the 20% baseline usage, but it is no surprise to me that it uses 99% of CPU when doing a scan - it's processing a significant amount of data.  @ceylina can you check and see if you can repro the 20% baseline? <3

**Comment by jrob8577** [comment] 2016-09-09 15:32
Also, @You-Too, can you post your system specs (just memory and CPU are fine). Curious to compare against other systems.

**Comment by ceylina** [comment] 2016-09-09 16:41
You may have a large amount of data stored from full scans. Auctionator is in use because of tooltip displays. If you have a large amount of stored full scans, it has to parse through your saved variable file and load that data. 

Try clearing your scans and it should dramatically decrease.

Cannot reproduce this. This is the "baseline" usage of auctionator (meaning no full scans stored)

![wowscrnshot_090916_114007](https://cloud.githubusercontent.com/assets/9342192/18395043/535c8c24-7682-11e6-98bd-4bdf46381b82.jpg)

**Comment by ceylina** [comment] 2016-09-09 16:46
Here is the option location to clear scanning history

![wowscrnshot_090916_114522](https://cloud.githubusercontent.com/assets/9342192/18395182/0e09a502-7683-11e6-8ecc-25b1b3aa8146.jpg)

**Comment by ceylina** [comment] 2016-09-09 16:55
Lastly, that is not 20% of your computer's cpu time. That is 20% of the in use CPU time for addons. So it is maybe less than 20% of 2% cpu usage on your PC meaning 1/10 of 1% total cpu max. In reality it doesn't even register unless you are on a computer 10+ years old.

**Comment by ceylina** [comment] 2016-09-09 16:57
Closing this as it doesn't impact game performance even at 20% of addon CPU usage.

**Closed by ceylina** 2016-09-09 16:57 UTC

**Comment by jrob8577** [comment] 2016-09-09 17:09
Thanks for the investigation and instructions @ceylina !!

**Comment by You-Too** [comment] 2016-09-11 15:20
Alright, thanks a lot! Not sure why it used 20% anyway. I did clear the scans and everything. I guess I'll try just resetting the addon by removing the saved variables altogether.

Not sure if it matters now that it's closed but I have an i7 920 @ 3.32ghz and 6gb DDR3 ram @ 1600mhz.
