### ISSUE TITLE
General wrath classic, Settings change error with Auctionator when I disabled "Show Helm." 

### ISSUE THREAD

**Issue by MelchiorGaspar** [Auctionator/Auctionator#1425] opened 2023-08-27 03:38 UTC
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug
I went to disable the "Show Helm" settings even though I currently at lv 22 do not have a helm equipped.. lol
and it popup up an error message to try and disable Auctionator which should not even have effected it..
so here I am to report it in case it is a bug..

## Steps to Reproduce

I went and checked in settings
GAME--> GamePlay --> Interface --> setting "Show Helm"
and decided to disable it to show my nice hair :D 
That's when the error occurred and BugSack caught it.

## Loaded Addons
pics from CurseForge addon manager.
![image](https://github.com/Auctionator/Auctionator/assets/1712842/c2ca5dd8-6d5b-4715-8a58-a2838021a3f6)
![image](https://github.com/Auctionator/Auctionator/assets/1712842/bc02a204-a4a9-4a1d-8867-516a2c9a1dc0)

## Back Trace (LUA Error Output)

1x [ADDON_ACTION_FORBIDDEN] AddOn 'Auctionator' tried to call the protected function 'SpellStopCasting()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `SpellStopCasting'
[string "@Interface_Wrath/FrameXML/UIParent.lua"]:3619: in function `ToggleGameMenu'
[string "@SharedXML/Settings/Blizzard_SettingsPanel.lua"]:340: in function `TransitionBackOpeningPanel'
[string "@SharedXML/Settings/Blizzard_SettingsPanel.lua"]:329: in function `ExitWithCommit'
[string "@SharedXML/Settings/Blizzard_SettingsPanel.lua"]:305: in function `Close'
[string "@SharedXML/Settings/Blizzard_SettingsPanel.lua"]:71: in function <SharedXML/Settings/Blizzard_SettingsPanel.lua:70>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

**Comment by plusmouse** [comment] 2023-08-27 12:37
This is bug, but a difficult one to fix as the error message doesn't include the information needed to figure out why it happened. That is normal for this kind of bug.

Can you run `/console taintLog 1`, cause the error and then close WoW and upload the contents of your `[WoW Directory]/_classic_/Logs/taint.log` file here. That should include the info I need to fix the issue.

**Comment by MelchiorGaspar** [comment] 2023-08-27 13:02
ok, will do. brb

**Comment by MelchiorGaspar** [comment] 2023-08-27 13:12
I ran the command "/console taintLog 1" at your request..
but for some reason the bug did not happen again..
and no log generated... :( XD

**Comment by plusmouse** [comment] 2023-08-27 13:16
That's OK. This kind of bug is difficult to reproduce, as its usually caused by some other interaction with Auctionator before the action that made the error show.

Now the taint log is on, when it eventually triggers again you'll get a log which I can use to fix it.

**Comment by MelchiorGaspar** [comment] 2023-08-27 13:19
aah yes.. ok I will report back if it should happen again..  :(

**Comment by MelchiorGaspar** [comment] 2023-08-28 03:43
still has not happened again.. 
I finally have a helm, 
"Azure Hood" for priest so cloth helm.
lol

**Comment by plusmouse** [comment] 2023-09-23 14:06
I'm going to close this issue. If it breaks again comment here (for me to reopen) or in a new issue. Hopefully it doesn't, but if it does you'll have a taint log this time around so I should be able to fix it properly

**Closed by plusmouse** 2023-09-23 14:06 UTC
Labels: classic

**Comment by MelchiorGaspar** [comment] 2023-09-23 15:46
ok, will do.
yeah it hasn't happened again since then thankfully..
