### ISSUE TITLE
4th TAB is occupied by another Auction House Addon

### ISSUE THREAD

**Issue by Kyphala** [Auctionator/Auctionator#700] opened 2020-05-01 07:06 UTC
## Brief Description of Bug

The 4th TAB in Auction houzse can also be used by other Addons (for example Trade Skill Master)
In this case TSM wins and you can't use Auctionator as ther is no TAB to call it.

## Steps to Reproduce

Have another Auction Addon running

**Comment by plusmouse** [comment] 2020-05-01 08:28
Duplicate of #643

**Closed by plusmouse** 2020-05-01 08:28 UTC
